// action types
const ADD_TO_BACKLOG          = 'ADD_TO_BACKLOG';
const MOVE_TO_NEXT_STATE      = 'MOVE_TO_NEXT_STATE';
const MOVE_TO_PREVIOUS_STATE  = 'MOVE_TO_PREVIOUS_STATE';

const TRANSITION = {ADD_TO_BACKLOG,
  MOVE_TO_NEXT_STATE,
  MOVE_TO_PREVIOUS_STATE};

export default TRANSITION;
